{% set name = "flashlfq" %}
{% set version = "0.1.99" %}
# Do not forget to update the version string in the searchgui.py file

about:
    home: https://github.com/smith-chem-wisc/FlashLFQ
    license: GLPL
    summary: ultrafast label-free quantification algorithm for mass-spectrometry proteomics

package:
    name: {{ name }}
    version: {{ version }}

build:
  number: 0

source:
    fn: FlashLFQ.zip
    url: https://github.com/smith-chem-wisc/FlashLFQ/releases/download/{{ version }}/FlashLFQ.zip
    md5: 4edaed42d563ee89bc4e6243a8e94a7a

requirements:
  build:
  run:
    - mono >=4.0.0

test:
    commands:
      - echo "" | FlashLFQ 2>1 | grep idt
